#ifndef fra_p_config_h
#define fra_p_config_h

#define FRA_CORE_DYNAMIC_ARRAYS_GROWTH_FACTOR 1.618f
#define FRA_CORE_DYNAMIC_ARRAYS_INITIAL_SIZE 10
#define FRA_CORE_WAITING_REQUESTS_GROWTH_FACTOR 1.618f
#define FRA_CORE_WAITING_ENDPOINT_STORES_GROWTH_FACTOR 1.618f
#define FRA_CORE_MAX_ENDPOINT_LENGTH 512
#define FRA_CORE_MAX_URL_LENGTH 512
#define FRA_CORE_MAX_VERB_LENGTH 50

#endif
